# -*- mode: ruby -*-
# vi: set ft=ruby :

load 'provision/config'

Vagrant.configure("2") do |config|

  # note: the box below already has a group 'apache' and user 'apache' with uid and gid 48
  config.vm.box = "fillup/centos-6.5-x86_64-minimal"
  config.vm.box_check_update = false
  config.vm.network :private_network, ip: PRIVATE_NETWORK_IP
  config.vm.hostname = HOSTNAME

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision :shell, :path => "provision/kickstart.sh"
  config.vm.provision :shell, :path => "provision/mariadb/mariadb.sh"
  config.vm.provision :shell, :path => "provision/java/java.sh"
  config.vm.provision :shell, :path => "provision/tomcat/tomcat.sh"
  config.vm.provision :shell, :path => "provision/lucee/lucee.sh"
  config.vm.provision :shell, :path => "provision/nginx/nginx.sh"
  config.vm.provision :shell, :path => "provision/custom/custom.sh"
  config.vm.provision :shell, :path => "provision/iptables/iptables.sh"
#  config.vm.provision :shell, :path => "provision/sendmail/sendmail.sh"

# remove for production systems, use ssh tunneling instead
# http://dnando.github.io/blog/2014/11/04/ssh-tunneling-coldfusion-lockdown-technique/
# https://github.com/apenwarr/sshuttle/blob/master/README.md
# config.vm.synced_folder "webapps", "/opt/tomcat/webapps", owner:"tomcat", group:"tomcat"
#  config.vm.synced_folder HOSTNAME, "/opt/tomcat/webapps/$HOSTNAME", owner:"root", group:"root"

end